# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'App_geod.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1083, 587)
        self.tab = QtWidgets.QTabWidget(Dialog)
        self.tab.setGeometry(QtCore.QRect(20, 20, 1031, 541))
        self.tab.setObjectName("tab")
        self.st10_2 = QtWidgets.QWidget()
        self.st10_2.setObjectName("st10_2")
        self.label_7 = QtWidgets.QLabel(self.st10_2)
        self.label_7.setGeometry(QtCore.QRect(10, 170, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(self.st10_2)
        self.label_2.setGeometry(QtCore.QRect(40, 290, 281, 16))
        self.label_2.setObjectName("label_2")
        self.p1992 = QtWidgets.QPushButton(self.st10_2)
        self.p1992.setGeometry(QtCore.QRect(400, 280, 121, 28))
        self.p1992.setObjectName("p1992")
        self.label_6 = QtWidgets.QLabel(self.st10_2)
        self.label_6.setGeometry(QtCore.QRect(10, 130, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.p2000 = QtWidgets.QPushButton(self.st10_2)
        self.p2000.setGeometry(QtCore.QRect(60, 360, 121, 28))
        self.p2000.setObjectName("p2000")
        self.elips = QtWidgets.QLabel(self.st10_2)
        self.elips.setGeometry(QtCore.QRect(10, 30, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.elips.setFont(font)
        self.elips.setObjectName("elips")
        self.label_4 = QtWidgets.QLabel(self.st10_2)
        self.label_4.setGeometry(QtCore.QRect(20, 240, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.st10_2)
        self.label_5.setGeometry(QtCore.QRect(360, 240, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.wynik10 = QtWidgets.QLabel(self.st10_2)
        self.wynik10.setGeometry(QtCore.QRect(0, 430, 451, 51))
        self.wynik10.setText("")
        self.wynik10.setObjectName("wynik10")
        self.filam = QtWidgets.QLabel(self.st10_2)
        self.filam.setGeometry(QtCore.QRect(10, 90, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.filam.setFont(font)
        self.filam.setObjectName("filam")
        self.FI = QtWidgets.QLineEdit(self.st10_2)
        self.FI.setGeometry(QtCore.QRect(40, 130, 141, 22))
        self.FI.setObjectName("FI")
        self.LAM = QtWidgets.QLineEdit(self.st10_2)
        self.LAM.setGeometry(QtCore.QRect(40, 170, 141, 22))
        self.LAM.setObjectName("LAM")
        self.Htab1 = QtWidgets.QLineEdit(self.st10_2)
        self.Htab1.setGeometry(QtCore.QRect(520, 150, 113, 22))
        self.Htab1.setObjectName("Htab1")
        self.label_3 = QtWidgets.QLabel(self.st10_2)
        self.label_3.setGeometry(QtCore.QRect(500, 150, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(self.st10_2)
        self.label_8.setGeometry(QtCore.QRect(380, 120, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.wynik92 = QtWidgets.QLabel(self.st10_2)
        self.wynik92.setGeometry(QtCore.QRect(330, 330, 301, 51))
        self.wynik92.setText("")
        self.wynik92.setObjectName("wynik92")
        self.label_13 = QtWidgets.QLabel(self.st10_2)
        self.label_13.setGeometry(QtCore.QRect(750, 240, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.XYZ = QtWidgets.QPushButton(self.st10_2)
        self.XYZ.setGeometry(QtCore.QRect(780, 270, 93, 28))
        self.XYZ.setObjectName("XYZ")
        self.wynikX = QtWidgets.QLabel(self.st10_2)
        self.wynikX.setGeometry(QtCore.QRect(670, 310, 321, 21))
        self.wynikX.setText("")
        self.wynikX.setObjectName("wynikX")
        self.GRS80 = QtWidgets.QRadioButton(self.st10_2)
        self.GRS80.setGeometry(QtCore.QRect(250, 40, 95, 20))
        self.GRS80.setObjectName("GRS80")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.GRS80)
        self.WGS84 = QtWidgets.QRadioButton(self.st10_2)
        self.WGS84.setGeometry(QtCore.QRect(160, 40, 71, 20))
        self.WGS84.setObjectName("WGS84")
        self.buttonGroup_2.addButton(self.WGS84)
        self.str6 = QtWidgets.QRadioButton(self.st10_2)
        self.str6.setGeometry(QtCore.QRect(70, 320, 41, 20))
        self.str6.setObjectName("str6")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.str6)
        self.str5 = QtWidgets.QRadioButton(self.st10_2)
        self.str5.setGeometry(QtCore.QRect(20, 320, 41, 20))
        self.str5.setObjectName("str5")
        self.buttonGroup.addButton(self.str5)
        self.str7 = QtWidgets.QRadioButton(self.st10_2)
        self.str7.setGeometry(QtCore.QRect(120, 320, 41, 20))
        self.str7.setObjectName("str7")
        self.buttonGroup.addButton(self.str7)
        self.str8 = QtWidgets.QRadioButton(self.st10_2)
        self.str8.setGeometry(QtCore.QRect(170, 320, 41, 20))
        self.str8.setObjectName("str8")
        self.buttonGroup.addButton(self.str8)
        self.wynikY = QtWidgets.QLabel(self.st10_2)
        self.wynikY.setGeometry(QtCore.QRect(670, 340, 321, 21))
        self.wynikY.setText("")
        self.wynikY.setObjectName("wynikY")
        self.wynikZ = QtWidgets.QLabel(self.st10_2)
        self.wynikZ.setGeometry(QtCore.QRect(670, 370, 321, 21))
        self.wynikZ.setText("")
        self.wynikZ.setObjectName("wynikZ")
        self.tab.addTab(self.st10_2, "")
        self.stopnie = QtWidgets.QWidget()
        self.stopnie.setObjectName("stopnie")
        self.elips_2 = QtWidgets.QLabel(self.stopnie)
        self.elips_2.setGeometry(QtCore.QRect(20, 30, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.elips_2.setFont(font)
        self.elips_2.setObjectName("elips_2")
        self.filam_3 = QtWidgets.QLabel(self.stopnie)
        self.filam_3.setGeometry(QtCore.QRect(20, 90, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.filam_3.setFont(font)
        self.filam_3.setObjectName("filam_3")
        self.label_14 = QtWidgets.QLabel(self.stopnie)
        self.label_14.setGeometry(QtCore.QRect(20, 160, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.stopnie)
        self.label_15.setGeometry(QtCore.QRect(20, 200, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label = QtWidgets.QLabel(self.stopnie)
        self.label.setGeometry(QtCore.QRect(90, 140, 55, 16))
        self.label.setObjectName("label")
        self.label_16 = QtWidgets.QLabel(self.stopnie)
        self.label_16.setGeometry(QtCore.QRect(200, 140, 55, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.stopnie)
        self.label_17.setGeometry(QtCore.QRect(310, 140, 55, 16))
        self.label_17.setObjectName("label_17")
        self.fist = QtWidgets.QLineEdit(self.stopnie)
        self.fist.setGeometry(QtCore.QRect(62, 160, 101, 22))
        self.fist.setObjectName("fist")
        self.fimin = QtWidgets.QLineEdit(self.stopnie)
        self.fimin.setGeometry(QtCore.QRect(170, 160, 101, 22))
        self.fimin.setObjectName("fimin")
        self.fisek = QtWidgets.QLineEdit(self.stopnie)
        self.fisek.setGeometry(QtCore.QRect(280, 160, 113, 22))
        self.fisek.setObjectName("fisek")
        self.lamst = QtWidgets.QLineEdit(self.stopnie)
        self.lamst.setGeometry(QtCore.QRect(60, 200, 101, 22))
        self.lamst.setObjectName("lamst")
        self.lammin = QtWidgets.QLineEdit(self.stopnie)
        self.lammin.setGeometry(QtCore.QRect(170, 200, 101, 22))
        self.lammin.setObjectName("lammin")
        self.lamsek = QtWidgets.QLineEdit(self.stopnie)
        self.lamsek.setGeometry(QtCore.QRect(280, 200, 113, 22))
        self.lamsek.setObjectName("lamsek")
        self.label_18 = QtWidgets.QLabel(self.stopnie)
        self.label_18.setGeometry(QtCore.QRect(20, 260, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.stopnie)
        self.label_19.setGeometry(QtCore.QRect(350, 260, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.stopnie)
        self.label_20.setGeometry(QtCore.QRect(40, 300, 181, 16))
        self.label_20.setObjectName("label_20")
        self.p2000_st = QtWidgets.QPushButton(self.stopnie)
        self.p2000_st.setGeometry(QtCore.QRect(60, 360, 121, 28))
        self.p2000_st.setObjectName("p2000_st")
        self.wynikst = QtWidgets.QLabel(self.stopnie)
        self.wynikst.setGeometry(QtCore.QRect(0, 430, 461, 51))
        self.wynikst.setText("")
        self.wynikst.setObjectName("wynikst")
        self.p1992_st = QtWidgets.QPushButton(self.stopnie)
        self.p1992_st.setGeometry(QtCore.QRect(390, 290, 121, 28))
        self.p1992_st.setObjectName("p1992_st")
        self.label_9 = QtWidgets.QLabel(self.stopnie)
        self.label_9.setGeometry(QtCore.QRect(570, 90, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.Htab2 = QtWidgets.QLineEdit(self.stopnie)
        self.Htab2.setGeometry(QtCore.QRect(700, 130, 113, 22))
        self.Htab2.setObjectName("Htab2")
        self.label_10 = QtWidgets.QLabel(self.stopnie)
        self.label_10.setGeometry(QtCore.QRect(670, 130, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.wynik92_2 = QtWidgets.QLabel(self.stopnie)
        self.wynik92_2.setGeometry(QtCore.QRect(320, 330, 301, 51))
        self.wynik92_2.setText("")
        self.wynik92_2.setObjectName("wynik92_2")
        self.label_12 = QtWidgets.QLabel(self.stopnie)
        self.label_12.setGeometry(QtCore.QRect(720, 260, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.XYZ_2 = QtWidgets.QPushButton(self.stopnie)
        self.XYZ_2.setGeometry(QtCore.QRect(750, 290, 93, 28))
        self.XYZ_2.setObjectName("XYZ_2")
        self.wynikXYZ_2 = QtWidgets.QLabel(self.stopnie)
        self.wynikXYZ_2.setGeometry(QtCore.QRect(640, 330, 321, 51))
        self.wynikXYZ_2.setText("")
        self.wynikXYZ_2.setObjectName("wynikXYZ_2")
        self.GRS80_st = QtWidgets.QRadioButton(self.stopnie)
        self.GRS80_st.setGeometry(QtCore.QRect(260, 40, 95, 20))
        self.GRS80_st.setObjectName("GRS80_st")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.GRS80_st)
        self.WGS84_st = QtWidgets.QRadioButton(self.stopnie)
        self.WGS84_st.setGeometry(QtCore.QRect(170, 40, 71, 20))
        self.WGS84_st.setObjectName("WGS84_st")
        self.buttonGroup_3.addButton(self.WGS84_st)
        self.str8_st = QtWidgets.QRadioButton(self.stopnie)
        self.str8_st.setGeometry(QtCore.QRect(170, 330, 41, 20))
        self.str8_st.setObjectName("str8_st")
        self.buttonGroup_4 = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup_4.setObjectName("buttonGroup_4")
        self.buttonGroup_4.addButton(self.str8_st)
        self.str5_st = QtWidgets.QRadioButton(self.stopnie)
        self.str5_st.setGeometry(QtCore.QRect(30, 330, 41, 20))
        self.str5_st.setObjectName("str5_st")
        self.buttonGroup_4.addButton(self.str5_st)
        self.str6_st = QtWidgets.QRadioButton(self.stopnie)
        self.str6_st.setGeometry(QtCore.QRect(80, 330, 41, 20))
        self.str6_st.setObjectName("str6_st")
        self.buttonGroup_4.addButton(self.str6_st)
        self.str7_st = QtWidgets.QRadioButton(self.stopnie)
        self.str7_st.setGeometry(QtCore.QRect(130, 330, 41, 20))
        self.str7_st.setObjectName("str7_st")
        self.buttonGroup_4.addButton(self.str7_st)
        self.wynikZ_2 = QtWidgets.QLabel(self.stopnie)
        self.wynikZ_2.setGeometry(QtCore.QRect(660, 390, 321, 21))
        self.wynikZ_2.setText("")
        self.wynikZ_2.setObjectName("wynikZ_2")
        self.wynikY_2 = QtWidgets.QLabel(self.stopnie)
        self.wynikY_2.setGeometry(QtCore.QRect(660, 360, 321, 21))
        self.wynikY_2.setText("")
        self.wynikY_2.setObjectName("wynikY_2")
        self.wynikX_2 = QtWidgets.QLabel(self.stopnie)
        self.wynikX_2.setGeometry(QtCore.QRect(660, 330, 321, 21))
        self.wynikX_2.setText("")
        self.wynikX_2.setObjectName("wynikX_2")
        self.tab.addTab(self.stopnie, "")

        self.retranslateUi(Dialog)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.WGS84, self.GRS80)
        Dialog.setTabOrder(self.GRS80, self.FI)
        Dialog.setTabOrder(self.FI, self.LAM)
        Dialog.setTabOrder(self.LAM, self.str5)
        Dialog.setTabOrder(self.str5, self.str6)
        Dialog.setTabOrder(self.str6, self.str7)
        Dialog.setTabOrder(self.str7, self.str8)
        Dialog.setTabOrder(self.str8, self.p2000)
        Dialog.setTabOrder(self.p2000, self.p1992)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_7.setText(_translate("Dialog", " <p>&lambda;</p>"))
        self.label_2.setText(_translate("Dialog", "Proszę wybrać strefę układu:"))
        self.p1992.setText(_translate("Dialog", "Przelicz do 1992"))
        self.label_6.setText(_translate("Dialog", "<p>&phi;</p> "))
        self.p2000.setText(_translate("Dialog", "Przelicz do 2000"))
        self.elips.setText(_translate("Dialog", "Wybierz elipsoidę:"))
        self.label_4.setText(_translate("Dialog", "Przeliczenie do układu 2000"))
        self.label_5.setText(_translate("Dialog", "Przeliczenie do układu 1992"))
        self.filam.setText(_translate("Dialog", "Wprowadź (stopnie dziesiętne):"))
        self.label_3.setText(_translate("Dialog", "h"))
        self.label_8.setText(_translate("Dialog", "Opcjonalnie (do przeliczenia XYZ):"))
        self.label_13.setText(_translate("Dialog", "Przeliczenie do XYZ:"))
        self.XYZ.setText(_translate("Dialog", "Przelicz"))
        self.GRS80.setText(_translate("Dialog", "GRS80"))
        self.WGS84.setText(_translate("Dialog", "WGS84"))
        self.str6.setText(_translate("Dialog", "6"))
        self.str5.setText(_translate("Dialog", "5"))
        self.str7.setText(_translate("Dialog", "7"))
        self.str8.setText(_translate("Dialog", "8"))
        self.tab.setTabText(self.tab.indexOf(self.st10_2), _translate("Dialog", "Stopnie dziesiętne"))
        self.elips_2.setText(_translate("Dialog", "Wybierz elipsoidę:"))
        self.filam_3.setText(_translate("Dialog", "Wprowadź:"))
        self.label_14.setText(_translate("Dialog", "<p>&phi;</p> "))
        self.label_15.setText(_translate("Dialog", " <p>&lambda;</p>"))
        self.label.setText(_translate("Dialog", "Stopnie"))
        self.label_16.setText(_translate("Dialog", "Minuty"))
        self.label_17.setText(_translate("Dialog", "Sekundy"))
        self.label_18.setText(_translate("Dialog", "Przeliczenie do układu 2000"))
        self.label_19.setText(_translate("Dialog", "Przeliczenie do układu 1992"))
        self.label_20.setText(_translate("Dialog", "Proszę wybrać strefę układu:"))
        self.p2000_st.setText(_translate("Dialog", "Przelicz do 2000"))
        self.p1992_st.setText(_translate("Dialog", "Przelicz do 1992"))
        self.label_9.setText(_translate("Dialog", "Opcjonalnie (do przeliczenia XYZ):"))
        self.label_10.setText(_translate("Dialog", "h"))
        self.label_12.setText(_translate("Dialog", "Przeliczenie do XYZ:"))
        self.XYZ_2.setText(_translate("Dialog", "Przelicz"))
        self.GRS80_st.setText(_translate("Dialog", "GRS80"))
        self.WGS84_st.setText(_translate("Dialog", "WGS84"))
        self.str8_st.setText(_translate("Dialog", "8"))
        self.str5_st.setText(_translate("Dialog", "5"))
        self.str6_st.setText(_translate("Dialog", "6"))
        self.str7_st.setText(_translate("Dialog", "7"))
        self.tab.setTabText(self.tab.indexOf(self.stopnie), _translate("Dialog", "Stopnie"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

